apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql_image
        imagePullPolicy: Never
        ports:
          - containerPort: 3306
            name: mysql
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: mysql-volume
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: mysql-volume-claim
