apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: nginx
  name: nginx-svc
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 192.168.99.103
  selector:
    app: nginx
  ports:
  - protocol: TCP
    name: ssh
    port: 22
    targetPort: 22
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
  - protocol: TCP
    name: https
    port: 443
    targetPort: 443
status:
  loadBalancer: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx_image
        name: nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 22
        - containerPort: 80
        - containerPort: 443
        resources: {}
status: {}
