FROM alpine:latest

#install
RUN apk update && apk upgrade
RUN apk add nginx openssl openssh openrc bash sudo supervisor
RUN apk add telegraf --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted

RUN adduser -D -g 'www' www
RUN mkdir /www
RUN chown -R www:www /var/lib/nginx
RUN chown -R www:www /www
RUN mkdir /run/nginx

#telegraf
RUN mkdir -p /etc/telegraf
COPY ./srcs/telegraf.conf /etc/telegraf/telegraf.conf

RUN	adduser -D wphylici \
	&& echo 'wphylici:wphylici' | chpasswd \
	&& addgroup wphylici wheel \
	&& echo '%wheel ALL=(ALL) ALL' > /etc/sudoers.d/wheel \
	&& /usr/bin/ssh-keygen -A

#openssl
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
	-keyout /etc/ssl/private/nginx-selfsigned.key \
	-out /etc/ssl/certs/nginx-selfsigned.crt \
	-subj "/C=RU/ST=Moscow/L=Moscow/O=School21/CN=wphylici"

COPY ./srcs/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./srcs/index.html /www/index.html

RUN mkdir -p /run/nginx
RUN mkdir /run/sshd
RUN chmod -R 777 /run/nginx
RUN chmod -R 777 /run/sshd
RUN chmod -R 777 /www

COPY ./srcs/supervisord.conf /etc/supervisord.conf

EXPOSE 80 443 22
CMD ["/usr/bin/supervisord"]